# Generated by Django 5.1.6 on 2025-02-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(verbose_name='About Heading')),
                ('title', models.CharField(max_length=255, verbose_name='About title')),
                ('description', models.TextField(verbose_name='About Desc.')),
                ('email', models.EmailField(max_length=255, verbose_name='About Email')),
                ('image', models.ImageField(upload_to='about_images/', verbose_name='About Image')),
                ('address', models.TextField(verbose_name='About Address')),
            ],
        ),
    ]
