# Generated by Django 5.1.6 on 2025-02-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.URLField(verbose_name="Facebook")),
                ("linkedin", models.URLField(verbose_name="LinkedIn")),
                ("github", models.URLField(verbose_name="GitHub")),
                (
                    "image_header",
                    models.ImageField(
                        upload_to="configuration_images/",
                        verbose_name="Configuration Image",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="favicons/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resumes/",
                        verbose_name="Resume PDF",
                    ),
                ),
            ],
        ),
    ]
