# Generated by Django 5.1.6 on 2025-02-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Project Name")),
                ("description", models.TextField(verbose_name="Project Desc.")),
                (
                    "icon",
                    models.CharField(
                        help_text="FontAwesome icon class, e.g., 'fa fa-shopping-cart'",
                        max_length=100,
                        verbose_name="Project Icon",
                    ),
                ),
                ("link", models.URLField(verbose_name="Project link")),
            ],
        ),
        migrations.AlterField(
            model_name="configuration",
            name="facebook",
            field=models.URLField(blank=True, null=True, verbose_name="Facebook"),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="github",
            field=models.URLField(blank=True, null=True, verbose_name="GitHub"),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="image_header",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="configuration_images/",
                verbose_name="Configuration Image",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="linkedin",
            field=models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
        ),
    ]
