# Generated by Django 5.1.6 on 2025-02-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_certificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Designation"),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "company",
                    models.CharField(max_length=255, verbose_name="Company Name"),
                ),
            ],
        ),
    ]
